### PR TITLE
SAE class agnostic functions

### PR DESCRIPTION
**Pull request by jordansauce**
I'm using some different SAE architectures to what you've got in your AutoEncoder class, but the regular `_get_dashboards_data()` and `get_prompt_data()` functions require an `AutoEncoder` as input, so I've broken these functions up:  `_get_dashboards_data()` and `get_prompt_data()` now respectively call `parse_dashboards_data()` and `parse_prompt_data()`, which take in only the required inputs, so that they're agnostic to the SAE or model architecture. Now we'll be able to import these functions and use them without relying on the `AutoEncoder` class. The same thing was done by Stefan in his https://github.com/ApolloResearch/rib_vis fork of your repo, and by Dan Braun and I within our private repo, but having these functions broken up in the main branch here will make it much easier to maintain compatibility.

There should have been no functional changes: just restructuring of the code. This has been tested by running demo.ipynb

### CODE REVIEW

**Comment by callummcdougall** [comment]
Hey, thanks for submitting this! I do feel kinda bad now because I have significantly restructured things (yet again). However after this restructure I'm planning to enable ppl like you and Joseph to make changes directly without going through me first. And hopefully these changes have not only added a few really cool and useful features (see [user guide](https://docs.google.com/document/d/1QGjDB3iFJ5Y0GGpTwibUVsvpnzctRSHRLI-0rm6wt_k/edit#heading=h.t3sp1uj6qghd)) but should also be more extensible and easier to edit. Let me know if you have any other thoughts!

As for the autoencoder thing specifically, yep I'd intended to change this (possibly to integrate with Joseph's Autoencoder class in that library, or else just make the function more permissive). Any edit here would be much appreciated!

**Comment by callummcdougall** [comment]
And for these changes specifically, lmk if there's anything else I can do to help!

**Comment by jordansauce** [comment]
All good no worries, the new features look great. So is this the last major restructure for a while, or is there another one coming down the pipe soon? If the latter, just let me know when it's out and I'll make these SAE-agnostic functions again.

**Comment by callummcdougall** [comment]
Definitely no more restructures planned! There may be additions, but
nothing major / no breaking changes. I anticipate that all future things
I'm interested in adding will be compatible with the current way that the
repo works (don't think that was the case before).

**Comment by jordansauce** [comment]
Excellent, I'll close this and make a new PR next week.

**Pull request closed without merging**
